### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by mthcht** [mthcht/ThreatHunting-Keywords#2]
- [x] Add every LOLBAS exploitation techniques we can fit in the list
  - [ ] check raw extract in https://github.com/mthcht/awesome-lists/blob/main/LOLBAS/lolbas_extract.txt
- [x] Add techniques and tactics for every tools (some are missing)
- [x] Test all the keywords for False positives again, i am also counting on valuable community feedbacks to help maintain a curated list of high-interest, low false-positive entries.
- [ ] release the other list with specific fields name to match each keywords (need more testing, not sure if relevant here since i have custom fields normalization)

**Comment by mthcht** [comment]
lolbas detections will be in a different lookups in the project https://github.com/mthcht/awesome-lists

**Comment by mthcht** [comment]
will not relase a different lookup with specific fields for now
